version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=NutriMatch
      - DB_USER=postgres
      - DB_PASSWORD=ber3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: NutriMatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ber3
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: